### ISSUE TITLE
don't use module in front end

### ISSUE THREAD

**Issue by abdhalees** [FACG2/200Palette#32]
module.exports isn't defined in browsers, you used in index.js 

![screenshot from 2017-08-03 09-21-46](https://user-images.githubusercontent.com/26231211/28908901-c5c17992-782e-11e7-8006-5376b90251a7.png)

**Comment by aajour** [comment]
great catch, thanks @abdhalees

**Comment by Walidmash** [comment]
@abdhalees we used it , to export the functions to the frontend test file , and it works in the test , but not in the browser, thanks again for the issue abd <3
